- src/main/java/com/sparta/hanghae66/dto/PostDto.java
- src/main/java/com/sparta/hanghae66/dto/UserRequestDto.java
- src/main/java/com/sparta/hanghae66/entity/Comment.java
- src/main/java/com/sparta/hanghae66/entity/CommentLikes.java
- src/main/java/com/sparta/hanghae66/entity/Post.java
- src/main/java/com/sparta/hanghae66/entity/PostLikes.java
- src/main/java/com/sparta/hanghae66/entity/RefreshToken.java
- src/main/java/com/sparta/hanghae66/entity/User.java
- src/main/java/com/sparta/hanghae66/jwt/JwtAuthFilter.java
- src/main/java/com/sparta/hanghae66/repository/CommentRepository.java
- src/main/java/com/sparta/hanghae66/repository/RefreshTokenRepository.java
- src/main/java/com/sparta/hanghae66/security/UserDetailsServiceImpl.java
- src/main/java/com/sparta/hanghae66/service/CommentService.java
- src/main/java/com/sparta/hanghae66/service/PostService.java
- src/main/java/com/sparta/hanghae66/service/UserService.java
- src/main/java/com/sparta/hanghae66/util/JwtUtil.java
> fix(레파지토리 최신화 오류관련 로직 수정

- src/main/java/com/sparta/hanghae66/dto/UserRequestDto.java
> fix(회원가입시 dto와 요청 원소값이 달라서 수정

- src/main/java/com/sparta/hanghae66/service/UserService.java
> fix(dto 변경관련 서비스 수정)

- src/main/java/com/sparta/hanghae66/Hanghae66Application.java
- src/main/java/com/sparta/hanghae66/config/WebSecurityConfig.java
- src/main/java/com/sparta/hanghae66/entity/Comment.java
> CORS정책 관련 configurer 추가

- src/main/java/com/sparta/hanghae66/controller/PostController.java
- src/main/java/com/sparta/hanghae66/service/UserService.java
> fix(게시글작성 컨트롤러 맵핑url 변경)

- src/main/java/com/sparta/hanghae66/Hanghae66Application.java
- src/main/java/com/sparta/hanghae66/controller/CommentController.java
- src/main/java/com/sparta/hanghae66/dto/CommentRequestDto.java
- src/main/java/com/sparta/hanghae66/dto/PostResponseDto.java
- src/main/java/com/sparta/hanghae66/entity/Comment.java
- src/main/java/com/sparta/hanghae66/entity/Post.java
- src/main/java/com/sparta/hanghae66/repository/CommentRepository.java
- src/main/java/com/sparta/hanghae66/repository/PostLikesRepository.java
- src/main/java/com/sparta/hanghae66/repository/PostRepository.java
- src/main/java/com/sparta/hanghae66/service/CommentService.java
- src/main/java/com/sparta/hanghae66/service/LikeService.java
- src/main/java/com/sparta/hanghae66/service/PostService.java
- src/main/java/com/sparta/hanghae66/service/UserService.java
- src/main/java/com/sparta/hanghae66/util/JwtUtil.java
> fix(전체 로직 점검 및 쿼리 수정진행)

- src/main/java/com/sparta/hanghae66/repository/CommentRepository.java
- src/main/java/com/sparta/hanghae66/service/PostService.java
> (fix 게시글 서비스 수정 : 글조회수 카운트되도록 수정, 댓글 리스트 안가져오는 오류 수정)

- src/main/java/com/sparta/hanghae66/entity/Comment.java
- src/main/java/com/sparta/hanghae66/repository/CommentLikesRepository.java
- src/main/java/com/sparta/hanghae66/service/LikeService.java
> fix(Spring) : 댓글 좋아요 카운팅 에러 수정

- src/main/java/com/sparta/hanghae66/repository/CommentLikesRepository.java
- src/main/java/com/sparta/hanghae66/service/LikeService.java
> chore (Spring) : repository 이전 ver으로 reset

- src/main/java/com/sparta/hanghae66/service/PostService.java
> (feat:조회시 코맨트 개수 카운트되도록 추가)

- src/main/java/com/sparta/hanghae66/Hanghae66Application.java
- src/main/java/com/sparta/hanghae66/service/PostService.java
> fix(CORS정책 모든 URL에서 요청되도록 수정)

- src/main/java/com/sparta/hanghae66/dto/CommentRequestDto.java
- src/main/java/com/sparta/hanghae66/dto/PostRequestDto.java
- src/main/java/com/sparta/hanghae66/service/LikeService.java
> style (Spring) : CommentRequestDto 변수명 수정

- src/main/java/com/sparta/hanghae66/controller/CommentController.java
- src/main/java/com/sparta/hanghae66/service/CommentService.java
> (fix: 코멘트 dto 수정하면서 get 명칭 재변경)

- src/main/java/com/sparta/hanghae66/controller/CommentController.java
- src/main/java/com/sparta/hanghae66/controller/UserController.java
- src/main/java/com/sparta/hanghae66/dto/CommentRequestDto.java
- src/main/java/com/sparta/hanghae66/service/CommentService.java
- src/main/java/com/sparta/hanghae66/service/UserService.java
> (feat: 로그아웃 기능 추가)

- src/main/java/com/sparta/hanghae66/controller/UserController.java
- src/main/java/com/sparta/hanghae66/dto/UserRequestDto.java
- src/main/java/com/sparta/hanghae66/service/UserService.java
> (feat:회원가입 아이디 중복체크시 유효성검사도 하도록 기능추가)

- src/main/java/com/sparta/hanghae66/dto/CommentDto.java
- src/main/java/com/sparta/hanghae66/dto/PostDto.java
- src/main/java/com/sparta/hanghae66/dto/PostResponseDto.java
- src/main/java/com/sparta/hanghae66/entity/Post.java
- src/main/java/com/sparta/hanghae66/repository/CommentLikesRepository.java
- src/main/java/com/sparta/hanghae66/service/PostService.java
늦게보내서 죄삼다
성윤님이 도와준 댓글 좋아요 기능입니다
> feat(Spring) : 댓글 좋아요 체크 API 추가

- src/main/java/com/sparta/hanghae66/controller/PostController.java
- src/main/java/com/sparta/hanghae66/service/PostService.java
> feat(게시글 조회시 쿠키로 중복조회 막도록 기능추가)

- src/main/java/com/sparta/hanghae66/dto/PostDto.java
- src/main/java/com/sparta/hanghae66/entity/Comment.java
- src/main/java/com/sparta/hanghae66/repository/CommentLikesRepository.java
- src/main/java/com/sparta/hanghae66/service/LikeService.java
- src/main/java/com/sparta/hanghae66/service/PostService.java
- src/main/java/com/sparta/hanghae66/service/UserService.java
> fix(Spring) : 댓글 좋아요 수가 없을 시 null 값으로 뜨는 오류 수정

- src/main/java/com/sparta/hanghae66/controller/PostController.java
- src/main/java/com/sparta/hanghae66/dto/PostRequestDto.java
> fix(Spring) : 게시글에 제목,내용,주특기 필터 추가

- src/main/java/com/sparta/hanghae66/entity/UserRole.java
- src/main/java/com/sparta/hanghae66/service/UserService.java
- src/main/java/com/sparta/hanghae66/util/JwtUtil.java
> fix:spring(유저권한 응답헤더로 리턴 추가 및 명칭 변경)
